name: infractions_app
description: "A Flutter project for Constatation des Infractions."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.8
  dio: ^5.3.3
  hive: ^2.2.3       
  hive_flutter: ^1.1.0  
  flutter_form_builder: ^9.1.1
  flutter_pdfview: ^1.3.1
  printing: ^5.10.0
  cached_network_image: ^3.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  fl_chart: ^0.68.0
  data_tables: ^1.1.1
  image_picker: ^0.8.7+5
  file_picker: ^8.0.0
  http: ^1.1.0
  camera: ^0.11.1+1
  fluttertoast: ^8.2.1
  another_flushbar: ^1.11.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Linting & best practices

flutter:
  uses-material-design: true

  assets:
    # Add your local assets here
    # - assets/images/
    # - assets/fonts/


